apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: adherence-copilot

resources:
  - namespace.yaml
  - postgres.yaml
  - backend.yaml
  - frontend.yaml
  - ingress.yaml # remove this line if you don't have an ingress controller
